fix: use pattern_id kwarg in registered model regex updates (#138)
Updating or deleting group regex registered model permissions is broken,
raises the following error:

```
│ app TypeError: update_group_registered_model_regex_permission() got an unexpected keyword argument 'pattern_id'  
```

I've tracked this down to inconsistency in the keyword argument for this
function, which expects to receive `id` instead of `pattern_id`.

`pattern_id` is specified as the appropriate kwarg in [the
route](https://github.com/mlflow-oidc/mlflow-oidc-auth/blob/b904ce7642aa4ac6a8c56e1bdefc709964458155/mlflow_oidc_auth/routes.py#L67-L68)
and is consistent with other functions that do work correctly like
[updating/deleting group_experiment_regex functionality.
](https://github.com/mlflow-oidc/mlflow-oidc-auth/blob/b904ce7642aa4ac6a8c56e1bdefc709964458155/mlflow_oidc_auth/views/group_experiment_regex.py#L41-L62)

Thanks. 

Sam